name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.3
  firebase_core: ^2.24.1
  firebase_messaging: ^14.7.7
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  url_launcher: ^6.2.2
  flutter_bloc: ^8.1.3
  kiwi: ^4.1.0
  dio: ^5.4.0
  quick_log: ^5.3.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  awesome_notifications:
  permission_handler: ^11.1.0
  intl: ^0.18.1
  firebase_analytics: ^10.7.3
  maps_launcher: ^2.2.0
  local_auth: ^2.1.8
  advance_pdf_viewer2: ^2.0.5+1
  lottie: ^3.0.0
  animate_do: ^3.3.1
  flutter_slidable: ^3.0.1
  flutter_html: ^3.0.0-beta.2
  pin_code_fields: ^8.0.1
  calendar_date_picker2: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svg/
    - assets/fonts/
    - assets/translations/


  fonts:
    - family: Switzer
      fonts:
        - asset: assets/fonts/switzer.otf
